config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :mappings
  get 'welcome/index'

  root 'mappings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mapping.rb
class Mapping < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  validates :username, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/mappings_controller.rb
class MappingsController < ApplicationController
  before_action :set_mapping, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /mappings
  # GET /mappings.json
  def index
    @mappings = Mapping.all
  end

  # GET /mappings/1
  # GET /mappings/1.json
  def show
  end

  # GET /mappings/new
  def new
    @mapping = Mapping.new
  end

  # GET /mappings/1/edit
  def edit
  end

  # POST /mappings
  # POST /mappings.json
  def create
    @mapping = Mapping.new(mapping_params)

    respond_to do |format|
      if @mapping.save
        format.html { redirect_to @mapping, notice: 'Mapping was successfully created.' }
        format.json { render :show, status: :created, location: @mapping }
      else
        format.html { render :new }
        format.json { render json: @mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mappings/1
  # PATCH/PUT /mappings/1.json
  def update
    respond_to do |format|
      if @mapping.update(mapping_params)
        format.html { redirect_to @mapping, notice: 'Mapping was successfully updated.' }
        format.json { render :show, status: :ok, location: @mapping }
      else
        format.html { render :edit }
        format.json { render json: @mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mappings/1
  # DELETE /mappings/1.json
  def destroy
    @mapping.destroy
    respond_to do |format|
      format.html { redirect_to mappings_url, notice: 'Mapping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mapping
      @mapping = Mapping.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mapping_params
      params.require(:mapping).permit(:regexstring, :direcory)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mappings_helper.rb
module MappingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_alerts.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-info ">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <= <%= link_to  "Dokuscanner", mappings_path, class: 'navbar-brand' %>>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <% if user_signed_in? %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                      <a class="nav-link" href="#">Link</a>
                  </li>
              </ul>
              <form class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
              </form>
          </div>
        <% elsif %>
           <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                      <%= link_to  "Sign Up", new_user_registration_path %>
                  </li>
                   <li class="nav-item active">
                      <%= link_to  "Log In", new_user_session_path %>
                  </li>
              </ul>
          </div>
        <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dokuscanner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class = container >
  <br/>
  <%= yield %>
</div>

</body>
</html>

app/views/mappings/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        New Mapping
      </div>
      <div class="card-body">
        <%= simple_form_for @mapping do |f| %>
          <%= f.input :regexstring ,label: 'Regular Expression to search in document'%>
          <%= f.input :direcory, label: 'Directory to move document if Regualr Expression was found' %>
          <%= f.button :submit ,'Save', class: 'btn btn-primary'%>
          <%= f.button :button, "Reset", type: "reset", class: "btn-outline-secondary" %>  
          <%= f.button :button, "Back", class: 'btn btn-secondary'%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/mappings/edit.html.erb
<h1>Editing Mapping</h1>

<%= render 'form', mapping: @mapping %>

<%= link_to 'Show', @mapping %> |
<%= link_to 'Back', mappings_path %>

app/views/mappings/index.html.erb
<%= render 'layouts/alerts' %>

<h1>Mappings</h1>
</br>

<table class= "table table-bordered table-striped ">
  <thead class="thead-dark">
    <tr>
      <th>Regexstring</th>
      <th>Direcory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mappings.each do |mapping| %>
      <tr>
        <td><%= mapping.regexstring %></td>
        <td><%= mapping.direcory %></td>
        <td><%= link_to 'Show', mapping %></td>
        <td><%= link_to 'Edit', edit_mapping_path(mapping) %></td>
        <td><%= link_to 'Destroy', mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mapping', new_mapping_path , class: 'btn btn-secondary' %>


<br> <br>

<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path) %>  
  </li>
<% end %>

app/views/mappings/new.html.erb
<%= render 'form', mapping: @mapping %>

<%= link_to 'Back', mappings_path %>

app/views/mappings/show.html.erb
<%= render 'layouts/alerts' %>

<p>
  <strong>Regexstring:</strong>
  <%= @mapping.regexstring %>
</p>

<p>
  <strong>Direcory:</strong>
  <%= @mapping.direcory %>
</p>

<%= link_to 'Edit', edit_mapping_path(@mapping) %> |
<%= link_to 'Back', mappings_path %>

app/views/welcome/index.html.erb
<div class="container">
  <h1>Welcome to Bootstrap 4</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et,  
     distinctio perspiciatis, fuga minus facilis ea quae qui laborum 
     cupiditate accusamus.
  </p>
  <button class="btn btn-primary">Button</button>
</div>